version: '3.7'
services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=jongbok
            - POSTGRES_DB=dataeng
        volumes: 
            - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"

        ports: 
            - 5432:5432
        

        logging:
            options:
                max-size: 10m
                max-file: "3"
    
    
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=jongbok.data0319@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=lee5506
        ports: 
            - "5050:80"
        
        

